# Using Org-Mode Dynamic Block
####+BEGIN: b:py3:pypi:setup/projectToml :comment "" :setuptoolsVer nil

[build-system]
requires = ["setuptools==75.8.0"]
build-backend = "setuptools.build_meta"

####+END:
